image: maven:3.6-jdk-12-alpine

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy_maven:
  stage: deploy
  only:
    - master
  script:
    - mvn $MAVEN_CLI_OPTS deploy

deploy_dropbox:
  stage: deploy
  only:
    - master
  variables:
    TARGET_FOLDER: "/Documents/JARs"
    UPLOADER_FETCH_URL: "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh"
    UPLOADER: "dropbox_uploader.sh"
    UPLOADER_CONFIG: "dropbox_uploader.cfg"
  before_script:
    - curl "${UPLOADER_FETCH_URL}" -o "${UPLOADER}"
    - echo "OAUTH_ACCESS_TOKEN=${DROPBOX_DEPLOY_TOKEN}" > "${UPLOADER_CONFIG}"
    - mvn $MAVEN_CLI_OPTS package
  script:
    - bash "${UPLOADER}" -f "${UPLOADER_CONFIG}" mkdir "${TARGET_FOLDER}" &>/dev/null || echo "Target folder exists"
    - bash "${UPLOADER}" -f "${UPLOADER_CONFIG}" upload builds/*.jar "${TARGET_FOLDER}"
  after_script:
    - rm -f "${UPLOADER}"
    - rm -f "${UPLOADER_CONFIG}"
